const dummyData = [
  { date: "2025-05-15", from: "newsletter@company.com", subject: "Your Monthly Digest is Here!" },
  { date: "2025-05-14", from: "support@service.com", subject: "Ticket #12345 Resolved" },
  { date: "2025-05-13", from: "no-reply@bank.com", subject: "Transaction Alert - $1,200.00 spent" },
  { date: "2025-05-12", from: "events@meetup.com", subject: "You're Invited: Tech Conference 2025" },
  { date: "2025-05-11", from: "info@jobboard.com", subject: "New Jobs Matching Your Profile" },
  { date: "2025-05-10", from: "alerts@security.com", subject: "Suspicious Login Attempt Detected" },
  { date: "2025-05-09", from: "team@openai.com", subject: "Your GPT-4 Subscription Receipt" },
  { date: "2025-05-08", from: "hello@travelnow.com", subject: "Spring Getaway Deals Inside" },
  { date: "2025-05-07", from: "contact@university.edu", subject: "Application Decision Update" },
  { date: "2025-05-06", from: "admin@yourapp.com", subject: "Welcome to YourApp!" },
  { date: "2025-05-05", from: "support@webmail.com", subject: "Reset Your Password" },
  { date: "2025-05-04", from: "billing@streaming.com", subject: "Your Invoice is Ready" },
  { date: "2025-05-03", from: "jobs@techcorp.com", subject: "We'd Like to Interview You" },
  { date: "2025-05-02", from: "update@software.com", subject: "Version 4.2 Released!" },
  { date: "2025-05-01", from: "offers@store.com", subject: "Big Sale: Up to 70% Off" },
  { date: "2025-04-30", from: "info@fitness.com", subject: "Your Weekly Fitness Report" },
  { date: "2025-04-29", from: "team@startup.com", subject: "Let's Collaborate on a Project" },
  { date: "2025-04-28", from: "notify@calendar.com", subject: "Reminder: Meeting at 2 PM" },
  { date: "2025-04-27", from: "service@host.com", subject: "Server Maintenance Scheduled" },
  { date: "2025-04-26", from: "newsletter@dailynews.com", subject: "Top Stories for Today" },
  { date: "2025-04-25", from: "inbox@cloudmail.com", subject: "Verify Your Email Address" },
  { date: "2025-04-24", from: "marketing@electronics.com", subject: "New Gadgets Just Arrived" },
  { date: "2025-04-23", from: "hi@reminders.com", subject: "You Missed a Task!" },
  { date: "2025-04-22", from: "learn@onlinecourse.com", subject: "Your Course Starts Tomorrow" },
  { date: "2025-04-21", from: "careers@company.com", subject: "Thank You for Applying" },
  { date: "2025-04-20", from: "feedback@survey.com", subject: "How Did We Do?" },
  { date: "2025-04-19", from: "updates@software.com", subject: "Patch Notes Available Now" },
  { date: "2025-04-18", from: "news@finance.com", subject: "Market Recap: Week in Review" },
  { date: "2025-04-17", from: "service@isp.com", subject: "Your Bill is Due" },
  { date: "2025-04-16", from: "offers@shopping.com", subject: "Flash Deals Ending Soon!" },
  { date: "2025-04-15", from: "security@bank.com", subject: "New Device Login Attempt" },
  { date: "2025-04-14", from: "hello@ecommerce.com", subject: "Thanks for Your Purchase!" },
  { date: "2025-04-13", from: "travel@booking.com", subject: "Your Itinerary is Confirmed" },
  { date: "2025-04-12", from: "info@webinar.com", subject: "Join Us Live This Friday" },
  { date: "2025-04-11", from: "alerts@app.com", subject: "App Update: New Features Added" },
  { date: "2025-04-10", from: "team@feedbackhub.com", subject: "We Value Your Input" },
  { date: "2025-04-09", from: "notify@social.com", subject: "You Have 3 New Messages" },
  { date: "2025-04-08", from: "admin@dashboard.com", subject: "Weekly Usage Summary" },
  { date: "2025-04-07", from: "reminder@tasks.com", subject: "Today’s Task List" },
  { date: "2025-04-06", from: "hi@contacts.com", subject: "John Doe Sent You a Request" },
  { date: "2025-04-05", from: "updates@newsfeed.com", subject: "Trending Topics Today" },
  { date: "2025-04-04", from: "deals@marketplace.com", subject: "Limited Time Discounts!" },
  { date: "2025-04-03", from: "info@service.com", subject: "Your Subscription is Expiring" },
  { date: "2025-04-02", from: "events@calendar.com", subject: "You’re Invited to Join" },
  { date: "2025-04-01", from: "hr@company.com", subject: "Onboarding Checklist" },
  { date: "2025-03-31", from: "support@forum.com", subject: "Your Question Has Been Answered" },
  { date: "2025-03-30", from: "info@tools.com", subject: "Boost Your Productivity" },
  { date: "2025-03-29", from: "hello@friends.com", subject: "Catch Up Soon?" },
  { date: "2025-03-28", from: "news@space.com", subject: "NASA Makes Breakthrough Discovery" }
];

export default dummyData;